# Generated by Django 3.1.7 on 2021-04-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20210323_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
