# Generated by Django 3.1.7 on 2021-04-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformUser',
        ),
    ]
